# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TritonGo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TritonGo
  pod 'GooglePlaces', '2.2.0'
  pod 'GoogleMaps', '2.2.0'
  pod 'GooglePlacePicker', '2.2.0'

  target 'TritonGo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TritonGoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TritonGo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


end
